baseURL = 'https://afternoon-web.com/'
defaultContentLanguage = "ja"
title = 'Afternoon Blog'
description = 'WEBエンジニアの技術ブログです。現在はPHP、Reactをメインの開発を行っています。それ以外にも興味がある技術を紹介しています。'
theme = 'PaperMod'
summaryLength = 10
hasCJKLanguage = true
googleAnalytics = 'G-8LBV6457JS'

[pagination]
  pagerSize = 10

[params]
  disableSpecial1stPost = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostMeta = true
  ShowReadingTime = false
  description = "WEBエンジニアの技術ブログです。現在はPHP、Reactをメインの開発を行っています。それ以外にも興味がある技術を紹介しています。"

[outputs]
  home = ['HTML', 'JSON']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    name = 'Search'
    url = '/search/'
    weight = 10

[[menu.main]]
    identifier = 'tags'
    name = 'tags'
    url = '/tags/'
    weight = 20

[[menu.main]]
    name = 'Archives'
    url = '/archives/'
    weight = 30

[[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 40

[[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 50

[[menu.footer]]
    name = 'プライバシーポリシー'
    url = '/privacy/'
    weight = 10    